# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import json
import logging
from typing import Optional
import httpx

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform.message import MessageChain, Plain

logger = logging.getLogger(__name__)



class DefaultEventListener(EventListener):
    def __init__(self):
        super().__init__()
        # Initialize configuration attributes
        self.api_base_url = None
        self.api_key = None
        self.workflow_id = None
        self.node_types = set()
        self.enable_metrics = True


    async def initialize(self):
        await super().initialize()
        # Register event handlers
        @self.handler(events.PersonMessageReceived)
        async def person_message_handler(event_context: context.EventContext):
            await self._handle_message(event_context)

        @self.handler(events.GroupMessageReceived)
        async def group_message_handler(event_context: context.EventContext):
            await self._handle_message(event_context)

    async def _handle_message(self, event_context: context.EventContext):
        """Handle incoming messages by preventing default behavior and processing via Dify workflow"""
        # Prevent default processing so we can handle the Dify workflow ourselves
        event_context.prevent_default()

        try:
            # Extract the message text
            message_text = self._extract_message_text(event_context.event.message_chain)
            if not message_text:
                await event_context.reply(
                    MessageChain([Plain(text="I didn't receive a valid message. Please try again.")])
                )
                return

            # Get plugin configuration
            config = self.plugin.get_config()
            api_base_url = config.get('api_base_url', 'https://api.dify.ai/v1').rstrip('/')
            api_key = config.get('dify_apikey', '')
            workflow_id = config.get('workflow_id', '')
            node_types = config.get('node_types', ['direct_output'])
            enable_metrics = config.get('enable_metrics', True)

            # Validate required configuration
            if not api_key:
                await event_context.reply(
                    MessageChain([Plain(text="Dify API key is not configured. Please contact the administrator.")])
                )
                return

            # Store config values for use in event handlers
            self.api_base_url = api_base_url
            self.api_key = api_key
            self.workflow_id = workflow_id
            self.node_types = set(node_types) if isinstance(node_types, list) else set()
            self.enable_metrics = enable_metrics

            logger.info(f"Processing message: {message_text[:100]}...")

            # Call Dify workflow API
            await self._invoke_dify_workflow(event_context, message_text)

        except Exception as e:
            logger.error(f"Error processing message: {e}", exc_info=True)
            await event_context.reply(
                MessageChain([Plain(text=f"An error occurred while processing your request: {str(e)}")])
            )

    def _extract_message_text(self, message_chain) -> Optional[str]:
        """Extract plain text from a message chain"""
        try:
            text_parts = []
            for segment in message_chain:
                if hasattr(segment, 'text'):
                    text_parts.append(segment.text)
                elif hasattr(segment, '__str__'):
                    text_parts.append(str(segment))
            return ''.join(text_parts).strip()
        except Exception:
            return None

    async def _invoke_dify_workflow(self, event_context: context.EventContext, query: str):
        """Invoke Dify workflow API with timeout"""
        url = f"{self.api_base_url}/workflows/run"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json"
        }

        payload = {
            "inputs": {},  # Empty inputs as we're passing the query as the main message
            "query": query,
            "response_mode": "streaming",
            "user": f"langbot_user_{id(event_context)}"
        }

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                async with client.stream('POST', url, json=payload, headers=headers) as response:
                    response.raise_for_status()

                    # Process the streaming response
                    async for line in self._process_sse_response(response.aiter_lines()):
                        await self._process_sse_line(event_context, line)

        except httpx.TimeoutException:
            await event_context.reply(
                MessageChain([Plain(text="Request to Dify timed out. Please try again.")])
            )
        except httpx.HTTPStatusError as e:
            await event_context.reply(
                MessageChain([Plain(text=f"Dify API error: {e.response.status_code} - {e.response.text}")])
            )
        except Exception as e:
            logger.error(f"Error calling Dify API: {e}", exc_info=True)
            await event_context.reply(
                MessageChain([Plain(text=f"Failed to connect to Dify service: {str(e)}")])
            )

    async def _process_sse_response(self, lines):
        """Process Server-Sent Events response"""
        buffer = ""
        async for line in lines:
            line = line.strip()
            if line == "":
                if buffer:
                    yield buffer
                    buffer = ""
            else:
                buffer += line + "\n"

        # Don't forget the last line if there's no trailing newline
        if buffer:
            yield buffer

    async def _process_sse_line(self, event_context: context.EventContext, line: str):
        """Process a single line from the SSE stream"""
        try:
            if not line.startswith("data: "):
                return

            data_str = line[6:]  # Remove "data: " prefix
            if not data_str.strip():
                return

            data = json.loads(data_str)
            event_type = data.get("event", "")
            event_data = data.get("data", {})

            # Handle different event types
            if event_type == "workflow_node_started":
                await self._handle_node_started_event(event_context, event_data)
            elif event_type == "workflow_node_finished":
                await self._handle_node_finished_event(event_context, event_data)
            elif event_type == "workflow_finished":
                await self._handle_workflow_finished_event(event_context, event_data)
            # Add other event types as needed

        except json.JSONDecodeError:
            # Invalid JSON, skip this line
            pass
        except Exception as e:
            logger.error(f"Error processing SSE line: {e}")

    async def _handle_node_started_event(self, event_context: context.EventContext, data: dict):
        """Handle workflow_node_started event"""
        node_type = data.get('node_type', '')
        node_id = data.get('id', '')
        node_title = data.get('title', '')
        workflow_run_id = data.get('workflow_run_id', '')

        # Check if this node type should trigger a notification
        if node_type in self.node_types:
            # Check workflow filter if specified
            if self.workflow_id and workflow_run_id != self.workflow_id:
                return

            # Send a notification that the node has started processing
            await self._send_node_notification(
                event_context,
                node_type,
                node_title,
                f"🔄 Starting to process node: {node_title}",
                is_start=True
            )

    async def _handle_node_finished_event(self, event_context: context.EventContext, data: dict):
        """Handle workflow_node_finished event"""
        node_type = data.get('node_type', '')
        node_id = data.get('id', '')
        node_title = data.get('title', '')
        workflow_run_id = data.get('workflow_run_id', '')
        status = data.get('status', 'unknown')
        outputs = data.get('outputs', {})

        # Check workflow filter if specified
        if self.workflow_id and workflow_run_id != self.workflow_id:
            return

        # Handle node failure
        if status == "failed":
            await self._send_node_notification(
                event_context,
                node_type,
                node_title,
                f"❌ Node processing failed: {node_title}",
                is_start=False
            )
            return

        # For successful nodes, check if we should output content
        if node_type in self.node_types:
            # Extract content from outputs (preferred) or inputs as fallback
            inputs = data.get('inputs', {})
            content = self._extract_node_content(outputs, inputs)
            if content:
                await self._send_node_notification(
                    event_context,
                    node_type,
                    node_title,
                    f"**Node Output**: {node_title}\n\n{content}",
                    is_start=False
                )

    async def _handle_workflow_finished_event(self, event_context: context.EventContext, data: dict):
        """Handle workflow_finished event to get the final answer"""
        workflow_run_id = data.get('workflow_run_id', '')
        status = data.get('status', 'unknown')
        outputs = data.get('outputs', {})

        # Check workflow filter if specified
        if self.workflow_id and workflow_run_id != self.workflow_id:
            return

        # Extract the final answer from outputs
        final_answer = self._extract_final_answer(outputs)

        if final_answer:
            await event_context.reply(MessageChain([Plain(text=final_answer)]))
        else:
            # Fallback: send a generic completion message
            status_emoji = "✅" if status == "succeeded" else "❌"
            await event_context.reply(
                MessageChain([Plain(text=f"{status_emoji} Workflow execution completed (status: {status})")])
            )

    def _extract_node_content(self, outputs: dict, inputs: dict) -> Optional[str]:
        """Extract content from node outputs or inputs"""
        # Try outputs first (preferred)
        if outputs and isinstance(outputs, dict):
            formatted = self._format_content(outputs)
            stripped = formatted.strip() if formatted else ""
            if stripped:
                return stripped

        # Fallback to inputs
        if inputs and isinstance(inputs, dict):
            formatted = self._format_content(inputs)
            stripped = formatted.strip() if formatted else ""
            if stripped:
                return stripped

        return None

    def _extract_final_answer(self, outputs: dict) -> Optional[str]:
        """Extract final answer from workflow outputs"""
        # Common patterns for final answer in Dify workflows
        if isinstance(outputs, dict):
            # Try common field names
            for key in ['text', 'answer', 'output', 'result']:
                if key in outputs and isinstance(outputs[key], str) and outputs[key].strip():
                    return outputs[key]

            # If outputs is a dict with a single string value, use that
            if len(outputs) == 1:
                value = next(iter(outputs.values()))
                if isinstance(value, str):
                    return value

        return None
    def _format_content(self, content: dict) -> str:
        """Format content dictionary as a readable string"""
        try:
            # Try to format as JSON with indentation for readability
            return json.dumps(content, ensure_ascii=False, indent=2)
        except (TypeError, ValueError):
            # Fallback to string representation
            return str(content)

    async def _send_node_notification(self, event_context: context.EventContext, node_type: str, node_title: str,
                                    message: str, is_start: bool):
        """Send a node notification message"""
        try:
            # Use the event context's reply method to send a message in the same conversation
            await event_context.reply(MessageChain([Plain(text=message)]))

            if self.enable_metrics:
                # In a full implementation, we would increment metrics here
                if is_start:
                    logger.debug(f"Sent start notification for node: {node_title}")
                else:
                    logger.debug(f"Sent completion notification for node: {node_title}")

        except Exception as e:
            logger.error(f"Failed to send node notification: {e}")
            # Don't fail the whole process if notification fails
