# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging
from langbot_plugin.api.definition.plugin import BasePlugin

logger = logging.getLogger(__name__)

class DifyNodeTypeAwarenessPlugin(BasePlugin):

    async def initialize(self) -> None:
        try:
            logger.info("DifyNodeTypeAwarenessPlugin 初始化")
            await super().initialize()
            logger.info("DifyNodeTypeAwarenessPlugin 初始化完成")
        except Exception as e:
            logger.error(f"DifyNodeTypeAwarenessPlugin 初始化失败: {e}", exc_info=True)
            raise

    def __del__(self) -> None:
        # Will be called when plugin is terminating
        logger.info("DifyNodeTypeAwarenessPlugin 卸载")

    async def destroy(self) -> None:
        """Clean up resources when the plugin is stopped."""
        if hasattr(super(), "destroy"):
            await super().destroy()
        logger.info("DifyNodeTypeAwarenessPlugin destroyed")