# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging
from langbot_plugin.api.definition.plugin import BasePlugin

logger = logging.getLogger(__name__)

class DifyNodeTypeAwarenessPlugin(BasePlugin):

    async def initialize(self) -> None:
        """Initialize the plugin."""
        try:
            logger.info("DifyNodeTypeAwarenessPlugin 初始化")
            await super().initialize()
            logger.info("DifyNodeTypeAwarenessPlugin 初始化完成")
        except Exception as e:
            logger.error(f"DifyNodeTypeAwarenessPlugin 初始化失败: {e}", exc_info=True)
            raise

    async def destroy(self) -> None:
        """Clean up resources when the plugin is stopped."""
        # Intentionally left empty to avoid any possible issues during shutdown
        # The base class should handle any necessary cleanup
        pass