# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging
from langbot_plugin.api.definition.plugin import BasePlugin

logger = logging.getLogger(__name__)

class DifyNodeTypeAwarenessPlugin(BasePlugin):

    async def initialize(self) -> None:
        # Will be called when plugin is launching
        logger.info("DifyNodeTypeAwarenessPlugin 初始化")
        await super().initialize()

    def __del__(self) -> None:
        # Will be called when plugin is terminating
        logger.info("DifyNodeTypeAwarenessPlugin 卸载")
